[package]
name = "start01"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.dev]
opt-level = "s"
panic = "abort"

[profile.release]
panic = "abort"

[target.'cfg(target_os = "windows")'.rustflags]
rustflags = ["-C", "link-args=/ENTRY:_start"]
